sites:
   ggl:
      name: Google
      url: https://google.com
   wkpd:
      name: Wikipedia
      url: https://wikipedia.org
   twt:
      name: Twitter
      url: https://twitter.com
   fcb:
      name: Facebook
      url: https://facebook.com
